# Generated by Django 4.0.6 on 2022-08-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=2000)),
                ('weight', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
                ('pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
