# Generated by Django 4.0.6 on 2022-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=2000)),
                ('body', models.CharField(max_length=65000)),
                ('pic', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
