# Generated by Django 4.0.6 on 2022-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='codename',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
