# Generated by Django 4.0.6 on 2022-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_productcategory_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=2000)),
                ('body', models.CharField(max_length=65000)),
                ('pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
